version: '2'

services:
  mgr2:
    image: greatsql/greatsql
    container_name: mgr2
    hostname: mgr2
    networks: 
      mgr_net:
        ipv4_address: 172.18.0.2
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_IBP: 512M
      MYSQL_INIT_MGR: 1
      MYSQL_MGR_NAME: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1
      MYSQL_MGR_LOCAL: '172.18.0.2:33061'
      MYSQL_MGR_SEEDS: '172.18.0.2:33061,172.18.0.3:33061,172.18.0.4:33061'
    extra_hosts:
      - "mgr2:172.18.0.2"
      - "mgr3:172.18.0.3"
      - "mgr4:172.18.0.4"
  mgr3:
    image: greatsql/greatsql
    container_name: mgr3
    hostname: mgr3
    networks: 
      mgr_net:
        ipv4_address: 172.18.0.3
    restart: unless-stopped
    depends_on:
      - "mgr2"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_IBP: 512M
      MYSQL_INIT_MGR: 1
      MYSQL_MGR_NAME: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1
      MYSQL_MGR_LOCAL: '172.18.0.3:33061'
      MYSQL_MGR_SEEDS: '172.18.0.2:33061,172.18.0.3:33061,172.18.0.4:33061'
    extra_hosts:
      - "mgr2:172.18.0.2"
      - "mgr3:172.18.0.3"
      - "mgr4:172.18.0.4"
  mgr4:
    image: greatsql/greatsql
    container_name: mgr4
    hostname: mgr4
    networks: 
      mgr_net:
        ipv4_address: 172.18.0.4
    restart: unless-stopped
    depends_on:
      - "mgr3"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_IBP: 512M
      MYSQL_INIT_MGR: 1
      MYSQL_MGR_NAME: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1
      MYSQL_MGR_LOCAL: '172.18.0.4:33061'
      MYSQL_MGR_SEEDS: '172.18.0.2:33061,172.18.0.3:33061,172.18.0.4:33061'
    extra_hosts:
      - "mgr2:172.18.0.2"
      - "mgr3:172.18.0.3"
      - "mgr4:172.18.0.4"
  mgr5:
    image: greatsql/greatsql
    container_name: mgr5
    hostname: mgr5
    networks: 
      mgr_net:
        ipv4_address: 172.18.0.5
    restart: unless-stopped
    depends_on:
      - "mgr4"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_IBP: 512M
      MYSQL_INIT_MGR: 1
      MYSQL_MGR_NAME: bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1
      MYSQL_MGR_LOCAL: '172.18.0.5:33061'
      MYSQL_MGR_SEEDS: '172.18.0.5:33061,172.18.0.6:33061,172.18.0.7:33061'
    extra_hosts:
      - "mgr5:172.18.0.5"
      - "mgr6:172.18.0.6"
      - "mgr7:172.18.0.7"
  mgr6:
    image: greatsql/greatsql
    container_name: mgr6
    hostname: mgr6
    networks: 
      mgr_net:
        ipv4_address: 172.18.0.6
    restart: unless-stopped
    depends_on:
      - "mgr5"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_IBP: 512M
      MYSQL_INIT_MGR: 1
      MYSQL_MGR_NAME: bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1
      MYSQL_MGR_LOCAL: '172.18.0.6:33061'
      MYSQL_MGR_SEEDS: '172.18.0.5:33061,172.18.0.6:33061,172.18.0.7:33061'
    extra_hosts:
      - "mgr5:172.18.0.5"
      - "mgr6:172.18.0.6"
      - "mgr7:172.18.0.7"
  mgr7:
    image: greatsql/greatsql
    container_name: mgr7
    hostname: mgr7
    networks: 
      mgr_net:
        ipv4_address: 172.18.0.7
    restart: unless-stopped
    depends_on:
      - "mgr6"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_IBP: 512M
      MYSQL_INIT_MGR: 1
      MYSQL_MGR_NAME: bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1
      MYSQL_MGR_LOCAL: '172.18.0.7:33061'
      MYSQL_MGR_SEEDS: '172.18.0.5:33061,172.18.0.6:33061,172.18.0.7:33061'
    extra_hosts:
      - "mgr5:172.18.0.5"
      - "mgr6:172.18.0.6"
      - "mgr7:172.18.0.7"
networks:
  mgr_net:
    ipam:
      config:
        - subnet: 172.18.0.0/24
