FROM docker.io/arm64v8/centos

LABEL maintainer="greatsql.cn" \
email="greatsql@greatdb.com" \
forum="https://greatsql.cn/forum.php" \
gitee="https://gitee.com/GreatSQL/GreatSQL-Docker"

ENV LANG en_US.utf8
ARG MYSQL_DATA_DIR=/data/GreatSQL \
MYSQL_USER=mysql \
MYSQL_UID_GID=3306 \
MYSQL_EXTRACT_DIR=/usr/local \
TMP_DIR=/tmp \
MYSQL_PORT=3306 \
DEPS="pkg-config perl libaio-devel numactl-devel numactl-libs \
net-tools openssl openssl-devel perl-Data-Dumper perl-Digest-MD5 \
python2 perl-JSON perl-Test-Simple" \
GREATSQL_INIT="greatsql-init.sh" \
GREATSQL_SHRINK="greatsql-shrink.sh" \
GREATSQL_TEST="greatsql-test.sql" \
GREATSQL_DOWNLOAD_URL="https://product.greatdb.com/GreatSQL-8.0.32-25" \
GREATSQL_RPMS1="greatsql-client-8.0.32-25.1.el8.aarch64.rpm" \
GREATSQL_RPMS2="greatsql-icu-data-files-8.0.32-25.1.el8.aarch64.rpm" \
GREATSQL_RPMS3="greatsql-server-8.0.32-25.1.el8.aarch64.rpm" \
GREATSQL_RPMS4="greatsql-shared-8.0.32-25.1.el8.aarch64.rpm"

CMD /bin/bash

RUN groupadd -g ${MYSQL_UID_GID} ${MYSQL_USER}; \
    useradd -u ${MYSQL_UID_GID} -r -g ${MYSQL_UID_GID} -s /sbin/nologin \
        -c "MySQL User" ${MYSQL_USER}

COPY ${GREATSQL_TEST} ${TMP_DIR}
COPY ${GREATSQL_INIT} /docker-entrypoint.sh
COPY ${GREATSQL_SHRINK} /tmp/{GREATSQL_SHRINK}
COPY my.cnf /etc/my.cnf

RUN unlink /etc/localtime; ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime ; \
rm -f /etc/yum.repos.d/CentOS-Linux-* ; \
curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-vault-8.5.2111.repo && \
sed -i -e '/mirrors.cloud.aliyuncs.com/d' -e '/mirrors.aliyuncs.com/d' /etc/yum.repos.d/CentOS-Base.repo && \
yum clean all > /dev/null 2>&1 && \
rm -f /etc/yum.repos.d/CentOS-Linux-* ; \
yum -y update > /dev/null 2>&1 ; \
yum clean all > /dev/null 2>&1 && \
rm -f /etc/yum.repos.d/CentOS-Linux-* ; \
yum install -y ${DEPS} > /dev/null 2>&1 ; \
yum install -y ${GREATSQL_DOWNLOAD_URL}/${GREATSQL_RPMS1} \
${GREATSQL_DOWNLOAD_URL}/${GREATSQL_RPMS2} \
${GREATSQL_DOWNLOAD_URL}/${GREATSQL_RPMS3} \
${GREATSQL_DOWNLOAD_URL}/${GREATSQL_RPMS4} && \
/bin/bash /tmp/{GREATSQL_SHRINK}

RUN echo "THP_SETTING=never" >> /etc/sysconfig/mysql

RUN mkdir -p ${MYSQL_DATA_DIR} && chown -R ${MYSQL_USER}:${MYSQL_USER} ${MYSQL_DATA_DIR}; chmod -R ug+rwX /etc/my.cnf

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE ${MYSQL_PORT} ${MYSQL_PORT}0 ${MYSQL_PORT}1
CMD ["mysqld"]
