SELECT '--- SELECT VERSION() ---';
SELECT @@version, @@version_comment;

SELECT '--- CREATE DB greatsql, GREATE TABLE t1, INSERT SOME ROWS, SELECT ROWS ---';
CREATE DATABASE IF NOT EXISTS greatsql;
USE greatsql;

CREATE TABLE t1(
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
c1 CLOB NOT NULL, 
c2 VARCHAR2(30) NOT NULL DEFAULT '',
c3 NUMBER UNSIGNED NOT NULL DEFAULT 0,
c4 PLS_INTEGER UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SHOW CREATE TABLE t1\G

INSERT INTO t1 VALUES 
(0, rand(), rand(), ROUND(RAND()*1024000), ROUND(RAND()*1024000)),
(0, rand(), rand(), ROUND(RAND()*1024000), ROUND(RAND()*1024000)),
(0, rand(), rand(), ROUND(RAND()*1024000), ROUND(RAND()*1024000)),
(0, rand(), rand(), ROUND(RAND()*1024000), ROUND(RAND()*1024000)),
(0, rand(), rand(), ROUND(RAND()*1024000), ROUND(RAND()*1024000)),
(0, rand(), rand(), ROUND(RAND()*1024000), ROUND(RAND()*1024000));

SELECT '--- SELECT ANY/ALL FROM t1 ---';
SELECT * FROM t1 WHERE id < ALL(9,19,29);
SELECT * FROM t1 WHERE id < ANY(9,19,29);

SELECT '--- SELECT SYSDATE UNDER DEFAULT MODE ---';
SELECT SYSDATE(), SYSDATE;

SELECT '--- SELECT SYSDATE UNDER ORACLE MODE ---';
SET sql_mode = ORACLE;
SELECT SYSDATE(), SYSDATE;

SELECT '--- LIST MGR MEMBERS ---';
SELECT MEMBER_ID, MEMBER_HOST, MEMBER_PORT, MEMBER_STATE, MEMBER_ROLE, MEMBER_VERSION FROM 
  performance_schema.replication_group_members;
