SELECT '--- SELECT VERSION() ---';
SELECT 'SELECT @@version, @@version_comment;' AS EXEC_TEST_SQL;
SELECT @@version, @@version_comment;

SELECT '--- CREATE DB greatsql, GREATE TABLE t1, INSERT SOME ROWS, SELECT ROWS ---';
SELECT 'CREATE DATABASE IF NOT EXISTS greatsql;' AS EXEC_TEST_SQL;
CREATE DATABASE IF NOT EXISTS greatsql;
SELECT 'USE greatsql;' AS EXEC_TEST_SQL;
USE greatsql;

SELECT '
CREATE TABLE t1(
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
c1 CLOB NOT NULL, 
c2 VARCHAR2(30) NOT NULL DEFAULT \'\',
c3 NUMBER UNSIGNED NOT NULL DEFAULT 0,
c4 PLS_INTEGER UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;' AS EXEC_TEST_SQL;
CREATE TABLE t1(
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
c1 CLOB NOT NULL, 
c2 VARCHAR2(30) NOT NULL DEFAULT '',
c3 NUMBER UNSIGNED NOT NULL DEFAULT 0,
c4 PLS_INTEGER UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SELECT 'SHOW CREATE TABLE t1\G' AS EXEC_TEST_SQL;
SHOW CREATE TABLE t1\G

SELECT 'INSERT INTO t1 VALUES 
(0, rand(), rand(), ROUND(RAND()*1024000), ROUND(RAND()*1024000)) ... ' AS EXEC_TEST_SQL;
INSERT INTO t1 VALUES 
(0, rand(), rand(), ROUND(RAND()*1024000), ROUND(RAND()*1024000)),
(0, rand(), rand(), ROUND(RAND()*1024000), ROUND(RAND()*1024000)),
(0, rand(), rand(), ROUND(RAND()*1024000), ROUND(RAND()*1024000)),
(0, rand(), rand(), ROUND(RAND()*1024000), ROUND(RAND()*1024000)),
(0, rand(), rand(), ROUND(RAND()*1024000), ROUND(RAND()*1024000)),
(0, rand(), rand(), ROUND(RAND()*1024000), ROUND(RAND()*1024000));

SELECT '--- SELECT ANY/ALL FROM t1 ---';
SELECT 'SELECT * FROM t1 WHERE id < ALL(9,19,29);' AS EXEC_TEST_SQL;
SELECT * FROM t1 WHERE id < ALL(9,19,29);
SELECT 'SELECT * FROM t1 WHERE id < ANY(9,19,29);' AS EXEC_TEST_SQL;
SELECT * FROM t1 WHERE id < ANY(9,19,29);

SELECT '--- SELECT SYSDATE UNDER DEFAULT MODE ---';
SELECT 'SELECT SYSDATE(), SYSDATE;' AS EXEC_TEST_SQL;
SELECT SYSDATE(), SYSDATE;

SELECT '--- SELECT SYSDATE UNDER ORACLE MODE ---';
SELECT 'SET sql_mode = ORACLE;' AS EXEC_TEST_SQL;
SET sql_mode = ORACLE;
SELECT 'SELECT SYSDATE(), SYSDATE;' AS EXEC_TEST_SQL;
SELECT SYSDATE(), SYSDATE;

SELECT '--- LIST MGR MEMBERS ---';
SELECT 'SELECT MEMBER_ID, MEMBER_HOST, MEMBER_PORT, MEMBER_STATE, MEMBER_ROLE, MEMBER_VERSION FROM 
  performance_schema.replication_group_members;' AS EXEC_TEST_SQL;
SELECT MEMBER_ID, MEMBER_HOST, MEMBER_PORT, MEMBER_STATE, MEMBER_ROLE, MEMBER_VERSION FROM 
  performance_schema.replication_group_members;
